<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>../../assets/app.ico</ApplicationIcon>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <RollForward>LatestPatch</RollForward>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../assets/app.ico" LogicalName="Oeps.AppIcon" />
    <ProjectReference Include="../Oeps.RawMaterialSticker.Core/Oeps.RawMaterialSticker.Core.csproj" />
    <Content Include="../../appsettings.json" Link="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../templates/*.zpl" Link="templates/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../samples/components.csv" Link="samples/components.csv" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Never" />
  </ItemGroup>
</Project>
